name: Label linked issues

on:
  push:
    branches:
      - main  # o cambia a la rama que uses

jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # importante: permite añadir etiquetas

    steps:
      - name: Extraer issues referenciados y etiquetarlos
        uses: actions/github-script@v7
        with:
          script: |
            const commitMessages = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            });

            const issuePattern = /#(\d+)/g;
            const issueNumbers = new Set();

            for (const commit of commitMessages.data) {
              let match;
              while ((match = issuePattern.exec(commit.commit.message)) !== null) {
                issueNumbers.add(match[1]);
              }
            }

            for (const issue_number of issueNumbers) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: Number(issue_number),
                labels: ['in progress']  // Cambia por la etiqueta que desees
              });
            }
